#pragma once

/**
 * xDrip Pebble Protocol constants.
 * Must match the Android side (PebbleProtocol.java) and package.json messageKeys.
 *
 * Protocol version is bumped only for breaking changes.
 * Keys are auto-generated by Pebble SDK from package.json messageKeys array.
 */

#define PROTOCOL_VERSION 1

// Message keys - must match xDrip's PebbleProtocol.java exactly
// We define these explicitly instead of using auto-generated MESSAGE_KEY_*
// because the Pebble SDK adds a 10000 offset to auto-generated keys
#define KEY_PROTOCOL_VERSION  0
#define KEY_CAPABILITIES      1
#define KEY_GRAPH_HOURS       2
#define KEY_TIMESTAMP         3
#define KEY_BG_MGDL           4
#define KEY_BG_MMOL_X10       5
#define KEY_TREND_ARROW       6
#define KEY_DELTA_MGDL        7
#define KEY_DELTA_MMOL_X10    8
#define KEY_IOB_MILLIUNITS    9
#define KEY_PUMP_STATE        10
#define KEY_PHONE_BATTERY     11
#define KEY_PUMP_BATTERY      12
#define KEY_GRAPH_DATA        13

// Capability bits (what data the watchface wants to receive)
#define CAP_BG_MGDL       (1 << 0)
#define CAP_BG_MMOL       (1 << 1)
#define CAP_TREND_ARROW   (1 << 2)
#define CAP_DELTA_MGDL    (1 << 3)
#define CAP_DELTA_MMOL    (1 << 4)
#define CAP_IOB           (1 << 5)
#define CAP_PUMP_STATE    (1 << 6)
#define CAP_PHONE_BATTERY (1 << 7)
#define CAP_PUMP_BATTERY  (1 << 8)
#define CAP_GRAPH_MGDL    (1 << 9)
#define CAP_GRAPH_MMOL    (1 << 10)

// Trend arrow values
#define ARROW_UNKNOWN     0
#define ARROW_DOUBLE_UP   1
#define ARROW_UP          2
#define ARROW_UP_RIGHT    3
#define ARROW_RIGHT       4
#define ARROW_DOWN_RIGHT  5
#define ARROW_DOWN        6
#define ARROW_DOUBLE_DOWN 7

// Default capabilities for PoC (mmol/L BG, trend arrow, delta)
#define DEFAULT_CAPABILITIES (CAP_BG_MMOL | CAP_TREND_ARROW | CAP_DELTA_MMOL)
